version: '3'

services:
  mysql:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=student_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./service-student/mysql_data:/var/lib/mysql

  postgresql:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=course_db
    volumes:
      - ./service-course/postgres:/var/lib/postgresql/data