version: '3'

services:
  mysql:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=student_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./service-student/mysql_data:/var/lib/mysql